# Generated by Django 4.1.4 on 2022-12-25 15:54

import authentification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default=authentification.utils.generate_token, max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
