# Generated by Django 4.1.4 on 2023-02-24 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='SocalLink',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
