# Generated by Django 4.1.4 on 2023-02-24 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sociallink_user_key_delete_socallink_sociallink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
