# Generated by Django 4.1.4 on 2023-02-28 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('viewed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('body', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('meta_name', models.CharField(choices=[('request', 'Request'), ('contract', 'Contract'), ('payment', 'Payment'), ('meterpoint', 'Meterpoint'), ('other', 'Other')], default='other', max_length=500)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
