# Generated by Django 4.1.4 on 2023-03-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='UAN', max_length=10)),
                ('order_id', models.CharField(default='', max_length=255)),
                ('card', models.CharField(default='**** **** **** 0000', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], default='pending', max_length=255)),
                ('payment_id', models.CharField(default='unknown', max_length=255)),
                ('acq_id', models.CharField(default='unknown', max_length=255)),
                ('liqpay_order_id', models.CharField(default='unknown', max_length=255)),
                ('transaction_id', models.CharField(default='unknown', max_length=255)),
                ('meta', models.TextField(blank=True, default='{}')),
                ('description', models.TextField(blank=True, default='')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_credit_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
