# Generated by Django 4.1.4 on 2022-12-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyMedia',
            new_name='RealEstateMedia',
        ),
    ]
