# Generated by Django 4.1.4 on 2022-12-29 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_realestate_animals_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatemedia',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_media_landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type_real_estate',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('appartment', 'Appartment'), ('single_room', 'Single room')], default='house', max_length=255),
        ),
    ]
