# Generated by Django 4.1.4 on 2022-12-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_realestatemedia_landlord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_landlord', 'Pending Landlord')], default='pending_landlord', max_length=255),
        ),
    ]
