# Generated by Django 4.1.4 on 2023-01-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_landlord', 'Pending Landlord'), ('pay_month', 'Pay Month'), ('pay_security', 'Pay Security'), ('terminated', 'Terminated')], default='pending_landlord', max_length=255),
        ),
    ]
