# Generated by Django 4.1.4 on 2023-01-01 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
