# Generated by Django 4.1.4 on 2023-01-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_transaction_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='token',
            new_name='liqpay_order_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_mask',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_card_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
