# Generated by Django 4.1.4 on 2023-01-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_transaction_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='liqpay_order_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
