# Generated by Django 4.1.4 on 2023-02-06 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0013_alter_transaction_liqpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('declined', 'Declined'), ('pending_landlord', 'Pending Landlord'), ('terminated', 'Terminated')], default='pending_landlord', max_length=255),
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(upload_to='meterpoints')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
                ('Other', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_contract', to='property.contract')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_landlord', to=settings.AUTH_USER_MODEL)),
                ('real_estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_real_estate', to='property.realestate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
