# Generated by Django 4.1.4 on 2023-02-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_contract_status_meterpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.contract'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank='', default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('rent', 'Rent'), ('internet', 'Internet'), ('gas', 'Gas'), ('water', 'Water'), ('electricity', 'Water'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
