# Generated by Django 4.1.4 on 2023-02-13 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0016_notion_notionmedia_request_requestmedia_contract_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('rent', 'Rent'), ('internet', 'Internet'), ('gas', 'Gas'), ('water', 'Water'), ('electricity', 'Electricity'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('period', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(upload_to='meterpoints')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
                ('other', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_contract', to='property.contract')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_creator', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_landlord', to=settings.AUTH_USER_MODEL)),
                ('real_estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_real_estate', to='property.realestate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_point_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
