# Generated by Django 4.1.4 on 2023-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_requestmedia_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='terminated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
