# Generated by Django 4.1.4 on 2023-03-13 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_contract_terminated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token', models.CharField(default='', max_length=255, null=True)),
                ('meta', models.TextField(blank=True, default='{}')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('success', 'Success'), ('processing', 'Processing'), ('pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
